require "fileutils"
require "lib/ruby/dynamic_pages"
require "lib/ruby/netlify"

include DynamicPages
include Netlify

module BuildEnvs
  MM_ENV = ENV["MM_ENV"]

  ##		=Core
  ########################################

  def coreConfig()
    set :layouts_dir, "views/layouts"

    # Page options
    page "/*.xml", layout: false
    page "/*.json", layout: false
    page "/*.txt", layout: false

    # Site variables
    set :SITE_TITLE, "Hansard Society"
    set :SITE_URL, ""

    # External pipeline:
    # Must run first since 'manifest_hash' is dependent
    # on 'rev-manifest.json', which is generated by gulp
    activate :external_pipeline,
      name: :gulp,
      command: "yarn run epipe:#{ MM_ENV == "dev" ? "dev" : "prod" }",
      source: ".tmp/assets",
      latency: 1

    # Dynamic pages
    dynamicContentfulPages(MM_ENV)
  end

  ##		=Build core
  ########################################

  def buildCore()

    ##		=Core
    ########################################

    # Core config
    coreConfig()

    # Vars
    @buildSrc = "build/#{ MM_ENV }"

    # Ignore
    ignore "assets/{[!fonts]}**"
    ignore "views/**"

    # relative links
    set :relative_links, true

    ##		=Cache busting
    ########################################

    manifest = File.read("source/assets/rev-manifest.json")
    manifest_hash = JSON.parse(manifest)

    cssAppHash = manifest_hash["app.css"]
    cssSnipcartHash = manifest_hash["snipcart.css"]
    cssVendorHash = manifest_hash["vendor.css"]
    jsAppHash = manifest_hash["app.js"]
    jsVendorHash = manifest_hash["vendor.js"]

    set :CSS_APP, "/assets/styles/#{ cssAppHash }"
    set :CSS_SNIPCART, "/assets/styles/#{ cssSnipcartHash }"
    set :CSS_VENDOR, "/assets/styles/#{ cssVendorHash }"
    set :JS_APP, "/assets/scripts/#{ jsAppHash }"
    set :JS_VENDOR, "/assets/scripts/#{ jsVendorHash }"

    set :build_dir, "build/#{ MM_ENV }"

    # Netlify
    redirects()

    # Pretty html filenames
    activate :directory_indexes

    # Enable gzip - implemented by Netlify
    # activate :gzip

    # Move assets
    def moveAssets(ext, dest)
      assetDest = "#{ @buildSrc }/assets/#{ dest }"

      FileUtils.mkdir_p assetDest
      FileUtils.mv Dir.glob("#{ @buildSrc }/*.#{ ext }"), assetDest
    end

    # After build
    after_build do

      # Redirects
      if MM_ENV == "prod"
        File.rename "build/prod/.redirects", "build/prod/_redirects"
      end

      # http/2 headers
      File.rename "#{ @buildSrc }/.headers", "#{ @buildSrc }/_headers"

      # Move assets
      moveAssets("css", "styles")
      moveAssets("js", "scripts")

      # Node scripts
      runNodeScripts = "yarn run post:#{ MM_ENV }"
      system runNodeScripts
    end
  end

  ##		=Production
  ########################################

  def buildProd()
    configure :prod do
      buildCore()

      set :ENV, "production"
      set :SNIPCART_TKN, ENV["SNIPCART_LIVE_TKN"]
    end
  end

  ##		=Preview
  ########################################

  def buildPreview()
    configure :preview do
      buildCore()

      set :ENV, "preview"
      set :SNIPCART_TKN, ENV["SNIPCART_PREVIEW_TKN"]
    end
  end

  ##		=Development
  ########################################

  def buildDev()
    configure :server do

      # Core config
      coreConfig()

      # Env variable
      set :ENV, "development"

      # Assets
      set :CSS_APP, "/app.css"
      set :CSS_SNIPCART, "/snipcart.css"
      set :CSS_VENDOR, "/vendor.css"
      set :JS_APP, "/app.js"
      set :JS_VENDOR, "/vendor.js"

      # Snipcart
      set :SNIPCART_TKN, ENV["SNIPCART_PREVIEW_TKN"]

      activate :directory_indexes
      activate :external_pipeline,
        name: :gulp,
        command: "yarn run epipe:dev",
        source: ".tmp/assets"
    end
  end
end
