source "https://rubygems.org"

gem "dotenv"
gem "bundler"
gem "kramdown"
gem "middleman"
gem "middleman-minify-html"
gem "slim"
gem "contentful_middleman", git: "https://github.com/contentful/contentful_middleman.git", branch: "v4-1.x-stable"
gem "public_suffix"
