source "https://rubygems.org"

gem "dotenv"
gem "bundler"
gem "kramdown"
gem "middleman-core", git: "https://github.com/middleman/middleman.git", branch: "master"
gem "middleman-cli", git: "https://github.com/middleman/middleman.git", branch: "master"
gem "slim"
gem "contentful_middleman", git: "https://github.com/contentful/contentful_middleman.git", branch: "v4-1.x-stable"
gem "public_suffix"
